.github/workflows/android-ci.yml
close #8 
- Android CI workflow_dispatch 적용
PR이 다음 요구 사항을 충족하는지 확인하세요. :
=> docs: Android CI workflow_dispatch 적용

.github/workflows/backend-ci.yml, .github/workflows/backend-dev-be.yml, .github/workflows/backend-dev.yml
- #18
- github actions workflow 생성
=> chore: github actions workflow 생성

.github/workflows/backend-ci.yml, .github/workflows/backend-dev.yml
=> fix: workflow 에러 수정

.github/workflows/backend-ci.yml, .github/workflows/backend-dev.yml
=> fix: scp 통신 제거

.github/workflows/backend-ci.yml, .github/workflows/backend-dev.yml
- close #4
- chore: prod 프로필로 빌드
=> chore: prod 프로필로 빌드

backend/build.gradle, backend/src/main/java/com/yagubogu/global/config/SwaggerConfig.java, backend/src/main/resources/application.yml
=> feat: Swagger 도입

android/app/build.gradle.kts, android/app/src/main/java/com/yagubogu/presentation/stats/StatsFragment.kt, android/app/src/main/java/com/yagubogu/presentation/stats/StatsFragmentStateAdapter.kt, android/app/src/main/res/layout/fragment_stats.xml, android/gradle/libs.versions.toml
- close #43 
- ViewPager2 라이브러리 추가
- 프래그먼트 간 슬라이드로 전환 구현
[Screen_recording_20250721_161948.webm](https://github.com/user-attachments/assets/aa614ae8-c166-408b-9ae9-fa4fe8a2d9a4)
=> feat: 통계 Fragment ViewPager2 구현

.github/workflows/backend-dev.yml, backend/src/main/resources/application.yml, backend/src/main/resources/yaml/application-dev.yml
- close #61 
- dev 프로필 추가 (개발 환경용)
=> chore: dev 프로필 추가

android/app/build.gradle.kts, android/app/src/main/AndroidManifest.xml, android/app/src/main/java/com/yagubogu/data/dto/response/StatCountsResponse.kt, android/app/src/main/java/com/yagubogu/data/dto/response/StatsCountsResponse.kt, android/app/src/main/java/com/yagubogu/data/network/RetrofitInstance.kt, android/app/src/main/java/com/yagubogu/data/service/StatsApiService.kt, android/app/src/main/res/xml/network_security_config.xml, android/gradle/libs.versions.toml
- close #59 
API 통신을 위한 Retrofit 기본 설정을 한다.
- 관련 의존성 추가 (Retrofit, kotlinx.serialization, retrofit.converter)
- `BuildConfig`에 BASE_URL 설정
- `RetrofitInstance` 생성
- OkHttp Logging Interceptor 적용
- `StatsApiService` 적용
=> feat: Retrofit 기본 설정

backend/src/main/java/com/yagubogu/member/controller/MemberController.java, backend/src/main/java/com/yagubogu/member/dto/MemberFavoriteResponse.java, backend/src/main/java/com/yagubogu/member/service/MemberService.java, backend/src/test/java/com/yagubogu/member/MemberIntegrationTest.java, backend/src/test/java/com/yagubogu/member/service/MemberServiceTest.java, backend/src/test/java/com/yagubogu/stadium/StadiumIntegrationTest.java, backend/src/test/java/com/yagubogu/stat/StatIntegrationTest.java
=> feat: 응원팀 조회 기능 구현

backend/src/main/java/com/yagubogu/checkin/repository/CheckInRepository.java, backend/src/main/java/com/yagubogu/global/GlobalExceptionHandler.java, backend/src/main/java/com/yagubogu/global/exception/dto/ExceptionResponse.java, backend/src/test/java/com/yagubogu/checkin/CheckInIntegrationTest.java, backend/src/test/java/com/yagubogu/stadium/service/StadiumServiceTest.java, backend/src/test/java/com/yagubogu/stat/StatIntegrationTest.java
- close #79
- close #80 
- ExceptionHandler 구현
- 구장별 팬 점유율 내림차순 수정
=> feat: ExceptionHandler 구현, 구장별 팬 점유율 내림차순 수정

backend/build.gradle
=> chore: springdoc 버전 2.7.0으로 수정

backend/src/main/java/com/yagubogu/checkin/repository/CheckInRepository.java, backend/src/main/java/com/yagubogu/member/dto/MemberFavoriteResponse.java, backend/src/main/java/com/yagubogu/team/domain/Team.java, backend/src/main/resources/data.sql, backend/src/test/java/com/yagubogu/member/domain/MemberTest.java, backend/src/test/resources/test-data.sql
- close #103 
- 응원팀 조회 기능, 구장별 팬 점유율 조회 기능 구현
=> feat: 응원팀 조회 기능, 구장별 팬 점유율 조회 기능 구현

.github/workflows/discord-notify.yml
- close #68 
- Discord 알림 케이스 추가(dev 브랜치를 대상으로 pr이 열렸을 때)
=> chore: Discord PR 알림 기능 추가

.github/workflows/issue-close.yml, .github/workflows/issue-setup.yml, .github/workflows/pr-setup.yml
- close #116 
- pr 생성시 `assignee` 설정, 라벨 추가, 리뷰어 설정, 프로젝트 설정, 마일스톤 설정 
- 이슈 생성시 `assignee` 설정, 라벨 추가, 리뷰어 설정, 프로젝트 설정, 마일스톤 설정 
- pr의 close, fix, resolve 키워드가 포함될 경우 연결된 이슈를 자동으로 닫아주는 기능 설정
=> [BE] pr, 이슈 관련 github actions workflow 추가

backend/src/main/java/com/yagubogu/team/domain/Team.java, backend/src/main/resources/data.sql, backend/src/test/java/com/yagubogu/member/domain/MemberTest.java, backend/src/test/resources/test-data.sql
- close #140
- team에 TeamCode 컬럼 추가
=> feat: team에 TeamCode 컬럼 추가

.github/workflows/android-ci.yml, android/.gitignore, android/app/build.gradle.kts, android/app/src/main/AndroidManifest.xml, android/app/src/main/java/com/yagubogu/YaguBoguApplication.kt, android/app/src/main/java/com/yagubogu/common/YaguBoguDebugTree.kt, android/app/src/main/java/com/yagubogu/common/YaguBoguReleaseTree.kt, android/app/src/main/java/com/yagubogu/presentation/home/HomeViewModel.kt, android/app/src/main/java/com/yagubogu/presentation/login/LoginActivity.kt, android/app/src/main/java/com/yagubogu/presentation/stats/my/MyStatsViewModel.kt, android/build.gradle.kts, android/gradle/libs.versions.toml
- close #189 
- Timber 라이브러리를 적용하여 debug/release 환경에서의 로그를 구분했습니다.
- BuildType을 활용하여 앱 빌드(debug, release)를 구분했습니다.
=> feat: 모니터링 환경 구축

backend/src/main/java/com/yagubogu/checkin/dto/CheckInGameTeamResponse.java, backend/src/main/java/com/yagubogu/checkin/repository/CheckInRepository.java, backend/src/test/java/com/yagubogu/checkin/service/CheckInServiceTest.java
- close #208 
- 당해 년도 직관 내역 최신순 조회에 팀 코드 추가
- [api 명세](https://www.notion.so/237ad073c10b8045922ef46b2d48d21e?source=copy_link) 변경완
=> feat: 당해 년도 직관 내역 최신순 조회에 팀 코드 추가

backend/src/main/resources/application.yml
=> chore: 토큰 유효기간 변경

backend/src/main/java/com/yagubogu/auth/controller/AuthController.java, backend/src/main/resources/application.yml
- #223 
- 토큰 유효기간 수정
- 리프레시 토큰 발급 권한 수정
=> feat: 토큰 유효기간 수정 및 리프레시 토큰 발급 권한 수정

backend/src/main/java/com/yagubogu/game/dto/GameWithCheckIn.java, backend/src/main/java/com/yagubogu/game/repository/GameRepository.java, backend/src/test/java/com/yagubogu/game/GameIntegrationTest.java, backend/src/test/java/com/yagubogu/game/service/GameServiceTest.java
- close #237 
- 게임 목록에 게임 id 추가
=> feat: 게임 목록에 게임 id 추가

backend/src/main/java/com/yagubogu/game/schedule/GameScheduler.java, backend/src/main/java/com/yagubogu/global/GlobalExceptionHandler.java, backend/src/main/java/com/yagubogu/global/LoggingInterceptor.java, backend/src/main/java/com/yagubogu/global/TransactionalLoggingAspect.java, backend/src/main/resources/log4j2-spring.xml
- close #251 
- [BE] Logging 구현
=> feat: [BE] Logging 구현

backend/src/main/java/com/yagubogu/checkin/controller/CheckInController.java, backend/src/main/java/com/yagubogu/checkin/controller/CheckInControllerInterface.java, backend/src/main/java/com/yagubogu/game/controller/GameController.java, backend/src/main/java/com/yagubogu/game/controller/GameControllerInterface.java, backend/src/main/java/com/yagubogu/member/controller/MemberController.java, backend/src/main/java/com/yagubogu/member/controller/MemberControllerInterface.java, backend/src/main/java/com/yagubogu/stadium/controller/StadiumController.java, backend/src/main/java/com/yagubogu/stadium/controller/StadiumControllerInterface.java, backend/src/main/java/com/yagubogu/stat/controller/StatController.java, backend/src/main/java/com/yagubogu/stat/controller/StatControllerInterface.java, backend/src/main/java/com/yagubogu/talk/controller/TalkController.java, backend/src/main/java/com/yagubogu/talk/controller/TalkControllerInterface.java
=> docs: Swagger 문서화

backend/src/main/java/com/yagubogu/auth/controller/AuthController.java, backend/src/main/java/com/yagubogu/auth/controller/AuthControllerInterface.java, backend/src/main/java/com/yagubogu/checkin/controller/CheckInControllerInterface.java, backend/src/main/java/com/yagubogu/game/controller/GameControllerInterface.java, backend/src/main/java/com/yagubogu/global/GlobalExceptionHandler.java, backend/src/main/java/com/yagubogu/global/config/WebConfig.java, backend/src/main/java/com/yagubogu/member/controller/MemberControllerInterface.java, backend/src/main/java/com/yagubogu/stat/controller/StatControllerInterface.java, backend/src/main/java/com/yagubogu/talk/controller/TalkControllerInterface.java
- close #262 
- 서버 예외 메세지 출력 오류 수정
=> fix: 서버 예외 메세지 출력 오류 수정

.github/workflows/discord-notify.yml
- close #269 
- 두리가 작업한 Discord PR 알림 커밋 체리픽
=> chore: 디스코드 PR 알림 workflow 체리픽

.github/workflows/backend-dev-be.yml, backend/src/main/java/com/yagubogu/auth/service/AuthService.java, backend/src/main/java/com/yagubogu/internal/controller/InternalAuthController.java, backend/src/main/java/com/yagubogu/internal/controller/InternalAuthControllerInterface.java, backend/src/main/java/com/yagubogu/internal/service/InternalAuthService.java, backend/src/main/resources/application-dev.yml
- close #274
- 내부 api : 회원 id로 토큰 발급하는 기능 구현 
=> feat: 내부 회원 api 구현

backend/src/main/resources/application-dev.yml, backend/src/main/resources/application-prod.yml
=> chore: 프로필 설정 수정

backend/src/test/java/com/yagubogu/auth/AuthIntegrationTest.java, backend/src/test/java/com/yagubogu/auth/config/AuthTestConfig.java, backend/src/test/java/com/yagubogu/checkin/CheckInIntegrationTest.java, backend/src/test/java/com/yagubogu/game/GameIntegrationTest.java, backend/src/test/java/com/yagubogu/member/MemberIntegrationTest.java, backend/src/test/java/com/yagubogu/support/TestSupport.java, backend/src/test/java/com/yagubogu/support/auth/AuthFactory.java, backend/src/test/java/com/yagubogu/support/checkin/CheckInBuilder.java, backend/src/test/java/com/yagubogu/support/checkin/CheckInFactory.java, backend/src/test/java/com/yagubogu/support/game/GameBuilder.java, backend/src/test/java/com/yagubogu/support/game/GameFactory.java, backend/src/test/java/com/yagubogu/support/member/MemberFactory.java, backend/src/test/java/com/yagubogu/support/talk/TalkBuilder.java, backend/src/test/java/com/yagubogu/support/talk/TalkFactory.java, backend/src/test/java/com/yagubogu/support/talk/TalkReportBuilder.java, backend/src/test/java/com/yagubogu/support/talk/TalkReportFactory.java
=> test: test.sql 제거 및 테스트 Fixture에 Builder 패턴 적용

backend/src/main/java/com/yagubogu/global/LoggingInterceptor.java, backend/src/main/java/com/yagubogu/global/TransactionalLoggingAspect.java, backend/src/main/java/com/yagubogu/global/config/WebConfig.java, backend/src/main/resources/log4j2-spring.xml
- close #306 
- transaction(read=only)도 로깅에 추가
- userId 로깅
- 파라미터 로깅
=> feat: Logging 고도화

backend/src/main/java/com/yagubogu/talk/repository/TalkRepository.java, backend/src/main/java/com/yagubogu/talk/service/TalkReportService.java, backend/src/test/java/com/yagubogu/talk/service/TalkServiceTest.java
- close #327 
- 신규 톡 폴링 조회 순서 반대로 하기
=> feat: 신규 톡 폴링 조회 순서 반대로 하기

.github/workflows/backend-dev.yml
* chore: docker 도입
* chore: workflow docker 도입
* chore: workflow 이름 변경
* fix: dockerfile 경로 수정
---------
- close #이슈번호
=> fix: dockerfile 경로 수정

.github/workflows/backend-dev.yml
* chore: docker 도입
* chore: workflow docker 도입
* chore: workflow 이름 변경
* fix: dockerfile 경로 수정
* chore: 스크립트 공백 제거
* chore: build 단계 제거
=> chore: 스크립트 공백 제거 및 빌드 단계 제거 (#344)

.github/workflows/backend-dev.yml, backend/Dockerfile
* chore: docker 도입
* chore: workflow docker 도입
* chore: workflow 이름 변경
* fix: dockerfile 경로 수정
* chore: 스크립트 공백 제거
* chore: build 단계 제거
* chore: 공백 제거
* chore: jdk 변경
---------
- close #346 
=> chore: jdk 변경 (#346)

.github/workflows/backend-main.yml, .github/workflows/backend-rollback-main.yml, backend/Dockerfile, backend/docker-compose.db.yml, backend/src/main/java/com/yagubogu/YaguboguApplication.java, backend/src/main/resources/application-prod.yml, backend/src/main/resources/db/schema.sql
=> chore: prod용 워크플로우 생성

.github/workflows/backend-main.yml, .github/workflows/backend-rollback-main.yml, backend/Dockerfile, backend/docker-compose.db.yml, backend/src/main/java/com/yagubogu/YaguboguApplication.java, backend/src/main/java/com/yagubogu/checkin/dto/FanRateGameEntry.java, backend/src/main/java/com/yagubogu/checkin/dto/FanRateResponse.java, backend/src/main/java/com/yagubogu/checkin/dto/GameWithFanCountsResponse.java, backend/src/main/java/com/yagubogu/checkin/repository/CheckInRepository.java, backend/src/main/java/com/yagubogu/checkin/service/CheckInService.java, backend/src/main/resources/application-prod.yml, backend/src/main/resources/db/schema.sql, backend/src/test/java/com/yagubogu/checkin/service/CheckInServiceTest.java
=> dev-be -> dev

.github/workflows/backend-main.yml
=> fix: 깃 태그 생성 버그 해결

.github/workflows/backend-dev.yml, .github/workflows/backend-main.yml
=> fix: 변수명 수정

.github/workflows/backend-dev.yml, .github/workflows/backend-main.yml
=> fix: 충돌 해결

.github/workflows/backend-dev.yml
- close #396 
- dev workflow runs-on 아키텍처 수정
- docker layer 캐시 추가
=> chore: dev workflow runs-on 아키텍처 수정, docker layer 캐시 추가

.github/workflows/backend-dev.yml
- close #396 
- dev workflow runs-on 아키텍처 수정
- docker layer 캐시 추가
=> chore: dev workflow runs-on 아키텍처 수정, docker layer 캐시 추가 (#397)

.github/workflows/backend-dev.yml
=> chore: 코드에 역슬래시 추가

backend/src/main/java/com/yagubogu/global/config/SwaggerConfig.java, backend/src/main/java/com/yagubogu/global/config/SwaggerUiServersProperties.java, backend/src/main/resources/application-dev.yml, backend/src/main/resources/application-prod.yml
- close #414 
- dev, prod swagger baseurl 분리해서 설정
- 
=> chore: dev, prod swagger baseurl 분리해서 설정

.github/workflows/backend-dev.yml, .github/workflows/backend-main.yml, backend/src/main/java/com/yagubogu/global/config/SwaggerConfig.java, backend/src/main/java/com/yagubogu/global/config/SwaggerUiServersProperties.java, backend/src/main/resources/application-dev.yml, backend/src/main/resources/application-prod.yml
- close #415 
- dev, prod swagger baseurl 분리해서 설정 
=> chore: dev, prod swagger baseurl 분리해서 설정 

android/app/src/main/java/com/yagubogu/presentation/stats/StatsFragment.kt, android/app/src/main/java/com/yagubogu/presentation/stats/my/StatsMyFragment.kt, android/app/src/main/java/com/yagubogu/presentation/stats/my/StatsMyUiModel.kt, android/app/src/main/java/com/yagubogu/presentation/stats/my/StatsMyViewModel.kt, android/app/src/main/java/com/yagubogu/presentation/stats/my/StatsMyViewModelFactory.kt, android/app/src/main/res/layout/fragment_stats_detail.xml, android/app/src/main/res/layout/fragment_stats_my.xml
- close #422 
- 상세 통계 RecyclerView 스크롤 효과 제거
- 최상위 layout을 NestedScrollView로 수정
- 내 통계 관련 파일 네이밍 `MyStats` -> `StatsMy`로 수정
=> design: 상세 통계 RecyclerView 스크롤 효과 제거

backend/src/main/java/com/yagubogu/auth/support/GoogleAuthValidator.java, backend/src/main/java/com/yagubogu/checkin/repository/CheckInRepository.java, backend/src/test/java/com/yagubogu/checkin/service/CheckInServiceTest.java, backend/src/test/java/com/yagubogu/support/TestFixture.java
=> fix: 직관 내역 조회 버그 수정

android/app/build.gradle.kts
- close #467 
- versionCode: 3 -> 4
- versionName: 0.3.0 -> 1.0.0
=> build: 야구보구 v1.0.0

android/app/src/main/java/com/yagubogu/presentation/livetalk/LivetalkFragment.kt, android/app/src/main/java/com/yagubogu/presentation/livetalk/LivetalkViewModel.kt
- close #493 
- 인증 한 경기장히 현장톡에서 가장 위로 올라갑니다
=> feat: 인증한 경기의 현장톡방을 가장 위에 표시

android/app/src/main/java/com/yagubogu/presentation/home/stadium/StadiumFanRateViewHolder.kt
- close #541 
- 오늘의 팬 현황 'VS' 텍스트 애니메이션 추가
- 사실 fragment가 hide 된 상황에서도 애니메이션이 계속 작동하는 성능 문제가 있을 것 같긴 한데요.. 크지 않을 거라 믿고 따로 해제하는 로직을 넣지 않았습니다. (나중에 개선하겠습니다. 컴포즈로 바꾸면서 없어질 거 같기도?)
https://github.com/user-attachments/assets/e9f1dca1-2c1d-446f-95de-24faa274aee6
=> design: 오늘의 팬 현황 'VS' 텍스트 애니메이션 추가

backend/src/main/java/com/yagubogu/like/dto/LikeBatchRequest.java, backend/src/main/java/com/yagubogu/like/repository/LikeWindowRepository.java, backend/src/main/java/com/yagubogu/like/service/LikeService.java, backend/src/main/resources/db/migration/mysql/V3__rename_user_column.sql, backend/src/test/java/com/yagubogu/like/LikeE2eTest.java
=> feat: memberId로 칼럼명 수정

backend/src/main/java/com/yagubogu/checkin/dto/FanRateByGameResponse.java, backend/src/main/java/com/yagubogu/checkin/dto/VictoryFairyRankingResponses.java, backend/src/test/java/com/yagubogu/checkin/CheckInE2eTest.java
=> fix: api 응답 추가된 것 삭제

backend/src/main/java/com/yagubogu/checkin/controller/CheckInController.java, backend/src/main/java/com/yagubogu/checkin/controller/CheckInControllerInterface.java, backend/src/main/java/com/yagubogu/checkin/service/CheckInService.java
=> fix: year 수정

backend/src/main/java/com/yagubogu/checkin/controller/CheckInController.java, backend/src/main/java/com/yagubogu/checkin/controller/CheckInControllerInterface.java, backend/src/main/java/com/yagubogu/checkin/service/CheckInService.java
=> fix: year 수정 (#572)

backend/src/main/java/com/yagubogu/checkin/dto/StatCounts.java, backend/src/main/java/com/yagubogu/checkin/repository/CustomCheckInRepository.java, backend/src/main/java/com/yagubogu/checkin/repository/CustomCheckInRepositoryImpl.java, backend/src/main/java/com/yagubogu/stat/service/StatService.java
=> refactor: 승/무/패 집계 쿼리를 하나로 통합

backend/build.gradle, backend/src/main/resources/application-prod.yml, backend/src/main/resources/application.yml
- close #516 
- hikcari Pool 모니터링을 위한 micrometer, prometheus endpoint 추가
=> chore: hikcari Pool 모니터링을 위한 micrometer, prometheus endpoint 추가

backend/src/main/java/com/yagubogu/checkin/dto/VictoryFairyRankingResponses.java, backend/src/main/java/com/yagubogu/checkin/repository/CustomCheckInRepositoryImpl.java, backend/src/main/java/com/yagubogu/checkin/service/CheckInService.java, backend/src/test/java/com/yagubogu/checkin/CheckInE2eTest.java, backend/src/test/java/com/yagubogu/checkin/service/CheckInServiceTest.java
=> fix: 승리요정 랭킹 중 인증 안 한 사람 제외

backend/src/main/java/com/yagubogu/sse/repository/SseEmitterRegistry.java
=> feat: sse 로깅 추가

backend/src/main/java/com/yagubogu/like/controller/LikeController.java, backend/src/main/java/com/yagubogu/like/controller/LikeControllerInterface.java, backend/src/main/java/com/yagubogu/like/dto/LikeBatchRequest.java, backend/src/main/java/com/yagubogu/like/dto/TeamLikeCountResponse.java, backend/src/main/java/com/yagubogu/like/repository/LikeRepository.java, backend/src/main/java/com/yagubogu/like/service/LikeService.java, backend/src/main/java/com/yagubogu/talk/controller/TalkController.java, backend/src/main/java/com/yagubogu/talk/controller/TalkControllerInterface.java, backend/src/main/java/com/yagubogu/talk/service/TalkService.java, backend/src/test/java/com/yagubogu/like/LikeE2eTest.java
- close #629 
- 불필요한 limit 파라미터 제거
- 좋아요 응답 필드에 memberId 제외 (헤더에서 Authorized token -> memberId 추출)
=> feat: 좋아요 수 응답 수정

backend/src/main/java/com/yagubogu/like/dto/TeamLikeCountResponse.java, backend/src/main/java/com/yagubogu/like/repository/LikeRepository.java, backend/src/test/java/com/yagubogu/like/LikeE2eTest.java
=> fix: 좋아요 응답 필드 수정 (null 비허용)

backend/src/main/java/com/yagubogu/like/dto/LikeBatchRequest.java, backend/src/main/java/com/yagubogu/like/service/LikeService.java, backend/src/test/java/com/yagubogu/like/LikeE2eTest.java
=> fix: 좋아요 배치 Request 필드 teamId -> teamCode로 수정
